# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-04 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20171204_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mess_txt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(default='ert', max_length=100),
            preserve_default=False,
        ),
    ]
